Changing the text for wrong file error
zeebe-io/zeebe-modeler pull request #256
Opened 2020-09-30 14:51 UTC by imrishabh18

__Which issue does this PR address?__

Closes #213 

__Acceptance Criteria__

* [ ] Corresponds to the concept 
* [ ] Corresponds to the design 

__Definition of Done__

* [ ] corresponds to [the design principles](https://github.com/bpmn-io/design-principles)
* [x] corresponds to [the code standards](https://github.com/bpmn-io/bpmn-js/blob/master/.github/CONTRIBUTING.md#creating-a-pull-request)
* [x] passes Continuous Integration checks
* [ ] available as feature branch on GitHub
  * [ ] contains the cleaned up commit history
  * [x] commit messages satisfy our [commit message guidelines](https://www.conventionalcommits.org/)
  * [x] a single commit closes the issue via Closes #213

2020-09-30 14:51 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/zeebe-io/zeebe-modeler?pullRequest=256) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/zeebe-io/zeebe-modeler?pullRequest=256) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/zeebe-io/zeebe-modeler?pullRequest=256) it.</sub>

2020-09-30 14:51 UTC, imrishabh18 commented
@pinussilvestrus Can you have a look at this?

2020-09-30 15:53 UTC, pinussilvestrus requested changes
Thanks! Before trying it out I see three improvements you can do

* Please update your commit message to fit our guidelines. Something like

```sh
fix(client/App): update text for wrong file error

Closes #213
```

* Can you think about a test case which verifies the fix?
* Can you please direct your PR to the master Branch? Bug fixes should always direct to this branch.

2020-09-30 16:24 UTC, imrishabh18 commented
I made the other two changes but I am not able to think of any test case for this and how do you even make them.

2020-09-30 17:51 UTC, pinussilvestrus requested changes
I suggested other, maybe better solutions for the problem. Besides, your commit message is still not valid. The current message is

```sh
Closes #213
```

the suggested message would be

```text
fix(client/App): update text for wrong file error

Closes #213
```

2020-09-30 17:51 UTC, pinussilvestrus commented on client/src/app/App.js
> +      seperator = '';
You tackled the correct helper function called `getOpenFileErrorDialog`. However, the seperator is not the root cause of this problem.

in the Zeebe Modeler we currently only have one single tab provider, that's why `providerNames` coming from the options is only including one provider name

```js
function getOpenFileErrorDialog(options) {
  const {
    name,
    providerNames
  } = options;

// providerNames = ['BPMN']

// ...

}
```

Therefore, the logic for getting the `providerNamesString` is not working for only one provider name and results in this weird dialog text. So I think a better solution would be either
1. Make the helper work in case the array has a size of 1
2. Simplify the whole function by only using the single array value

2020-10-10 18:18 UTC, pinussilvestrus commented
@imrishabh18 any updates on this? Do you need help?

2020-10-11 15:58 UTC, imrishabh18 commented on client/src/app/App.js
> +      seperator = '';
Okay, Can you explain a bit about how to only run the helper function only if the array size is 1?

2020-10-12 09:58 UTC, pinussilvestrus commented on client/src/app/App.js
> +      seperator = '';
> how to only run the helper function only if the array size is 1?

why you would want to do it? What I mean is to update the helper function to make it aware for the case the `providerNames` is a single value array. Currently, it doesn't do it.

2020-10-19 09:44 UTC, pinussilvestrus commented on client/src/app/App.js
> +    } else if(isLast && providerNames.length === 1) {
Personally, I'd change the if-else order

```js
if(providerNames.length == 1) {
  seperator = '';
} else if (isLast) {
   seperator = ' or ';
} else if (!isFirst) {
    seperator = ', ';
} 
```

or even outside of the `reduce` function

```js
let providerNamesString;

if(providerNames.length == 1) {
  providerNamesString = providerNames[0];
} else {
  
  // the current logic
  providerNamesString = providerNames.reduce(...)
}
```

2020-10-22 07:24 UTC, pinussilvestrus commented on client/src/app/App.js
> +    } else if(isLast && providerNames.length === 1) {
@imrishabh18 any thoughts?

2020-11-01 03:37 UTC, vvkpd commented
I would like to contribute on this card

2020-11-01 11:00 UTC, imrishabh18 commented on client/src/app/App.js
> +    } else if(isLast && providerNames.length === 1) {
Okay, I will change the if-else order then @pinussilvestrus

2020-11-10 08:59 UTC, pinussilvestrus commented on client/src/app/App.js
> +    } else if(isLast && providerNames.length === 1) {
Any updates on this @imrishabh18 ? Can we move forward?

2020-11-16 08:02 UTC, pinussilvestrus commented
I'm closing this since no updates were done for a time now. Feel free to re-open it once we can proceed.

2020-11-16 08:02 UTC, closed without merging