feat: support propagateAllChildVariables attribute on callActivities
zeebe-io/zeebe-modeler pull request #271
Opened 2020-11-09 10:08 UTC by MaxTru

!--

Thanks for creating this pull request!

Please make sure you provide the relevant context.

-->

__Which issue does this PR address?__

Ccloses #252
Closes #267

__Acceptance Criteria__

This commit includes three key changes to support the new
propagateAllChildVariables attribute on calledElement extensionElements:
(1): Behavior to initialize callActivities with
propagateAllChildVariables set to false per default (CreateZeebeCallActivityBehavior)
(2): toogle UI component to controll the attribute and to display it
accordingly to engine logic in case it is not set (legacy diagrams)
(OutputParameterToggle)
(3): behavior to keep the attribute in sync with outputParameters
(UpdatePropagateAllChildVariablesBehavior)

* [ ] Corresponds to the concept 
* [ ] Corresponds to the design 

__Definition of Done__

* [ ] corresponds to [the design principles](https://github.com/bpmn-io/design-principles)
* [ ] corresponds to [the code standards](https://github.com/bpmn-io/bpmn-js/blob/master/.github/CONTRIBUTING.md#creating-a-pull-request)
* [ ] passes Continuous Integration checks
* [ ] available as feature branch on GitHub
  * [ ] contains the cleaned up commit history
  * [ ] commit messages satisfy our [commit message guidelines](https://www.conventionalcommits.org/)
  * [ ] a single commit closes the issue via Closes #issuenr

2020-11-09 10:46 UTC, MaxTru commented
Provided artifact to @andreasgeier and @volkergersabeck for Design and PM review as well

2020-11-11 08:23 UTC, pinussilvestrus commented
Regarding 79e0a81039a96a979689858cb0c64fc048f5011c: the commit itself is really complex and seems to fix / add 2-3 things at the same time. Do we have any chance to split the changes up?

2020-11-11 08:25 UTC, MaxTru commented
> Regarding [79e0a81](https://github.com/zeebe-io/zeebe-modeler/commit/79e0a81039a96a979689858cb0c64fc048f5011c): the commit itself is really complex and seems to fix / add 2-3 things at the same time. Do we have any chance to split the changes up?

Will do

2020-11-12 10:48 UTC, MaxTru commented
PM and Design review done, ready for code review

2020-11-13 10:04 UTC, pinussilvestrus commented
After we split up the commits, we should ensure we reference the closing commits in some of them.

2020-11-13 10:12 UTC, MaxTru commented
> After we split up the commits, we should ensure we reference the closing commits in some of them.
:facepalm: 

Forgot it... sorry. Will do.

2020-11-13 10:31 UTC, MaxTru commented
> After we split up the commits, we should ensure we reference the closing commits in some of them.

Done and commit split

2020-11-13 10:42 UTC, pinussilvestrus requested changes
Generally, it works really smooth and I like the changes a lot 👍 

Some recommendations to make implementation and tests clearer, to avoid confusion in the future.

2020-11-13 10:42 UTC, pinussilvestrus commented on client/src/app/tabs/bpmn/custom/modeling/__tests__/CreateZeebeCallActivityBehaviorSpec.js
> +      it('should not duplicate extensionElements', inject(function(canvas,
I don't understand the header of this test case. From my understanding when copying a call activity, the extension elements got indeed copied, the test is also verifying it. So isn't it rather

> it should duplicate extensionElements

?

2020-11-13 10:42 UTC, pinussilvestrus commented on client/src/app/tabs/bpmn/custom/modeling/__tests__/UpdatePropagateAllChildVariablesBehaviorSpec.js
> +      describe('parameter not explicitly set (legacy callActivity)', function() {
with "parameter" we mean `propagateAllChildVariables` right? Maybe we should use

> \<propagateAllChildVariables\> not explicitly set (legacy callActivity)

to avoid confusion since we use "outputParameters" in the same term.

2020-11-13 10:42 UTC, pinussilvestrus commented on client/src/app/tabs/bpmn/custom/modeling/__tests__/UpdatePropagateAllChildVariablesBehaviorSpec.js
> +  describe('set propagateAllChildVariables to false', function() {
What we are currently testing here are the created output parameters. What we should test is the `propagateAllChildVariables` property after adding the output parameters.

2020-11-13 10:42 UTC, pinussilvestrus commented on client/src/app/tabs/bpmn/custom/modeling/behavior/CreateZeebeCallActivityBehavior.js
> +    if (!calledElement) {
I'd switch the order

first: assure `calledElement` exists, if not, create it (where you also can set the property to false)
second: assure `propagateAllChildVariables` property is set to false, if not, set it.

2020-11-13 10:42 UTC, pinussilvestrus commented on client/src/app/tabs/bpmn/custom/modeling/behavior/UpdatePropagateAllChildVariablesBehavior.js
> +    // (1) Check whether we are in a CallActivity and un-toggling propAllChildVariables
would not say "un-toggling", one might not understand it. It should be generally checking whether we are setting propAllChildVariables to true (or undefined?)

2020-11-13 10:42 UTC, pinussilvestrus commented on client/src/app/tabs/bpmn/custom/modeling/behavior/UpdatePropagateAllChildVariablesBehavior.js
> +        !!properties.propagateAllChildVariables === false) {
why do we need the `!!` ?

2020-11-13 10:42 UTC, pinussilvestrus commented on client/src/app/tabs/bpmn/custom/modeling/behavior/UpdatePropagateAllChildVariablesBehavior.js
> +    if (oldOutputParameters) {
It trusts that no other command is using this property, but should be fine.

2020-11-13 10:42 UTC, pinussilvestrus commented on client/src/app/tabs/bpmn/custom/modeling/behavior/UpdatePropagateAllChildVariablesBehavior.js
> +  // Behavior when adding outputParmaeters ////////////////////////////////////
typo: `outputParameters`

2020-11-13 10:42 UTC, pinussilvestrus commented on client/src/app/tabs/bpmn/custom/modeling/behavior/UpdatePropagateAllChildVariablesBehavior.js
> +     (objectsToAdd && objectsToAdd.length > 0 && !is(objectsToAdd[0], 'zeebe:Output')) ||
Not doable via properties panel currently, but maybe relevant: What happens if we use the command with a `objectsToAdd` like this (short form)

```js
[
  'zeebe:Input',
  'zeebe:Output',
  'zeebe:Output'
]
```

Don't know whether this is possible at all, but then the behavior would not proceed, since _the first added parameter is an input_. Maybe we should simply check via `filter` whether at least one `zeebe:Output` was added.

2020-11-13 10:42 UTC, pinussilvestrus commented on client/src/app/tabs/bpmn/custom/modeling/behavior/UpdatePropagateAllChildVariablesBehavior.js
> +  // Revert behavior when adding outputParmaeters ////////////////////////////////////
typo: `outputParameters`

2020-11-13 10:42 UTC, pinussilvestrus commented on client/src/app/tabs/bpmn/custom/properties-provider/__tests__/InputOutputSpec.js
> +import contextPadModule from 'bpmn-js/lib/features/context-pad';
why do we need contextPad and palette here?

2020-11-13 10:42 UTC, pinussilvestrus commented on client/src/app/tabs/bpmn/custom/properties-provider/__tests__/OutputParameterToggleSpec.js
> +
additional new line needed

2020-11-13 14:40 UTC, MaxTru commented on client/src/app/tabs/bpmn/custom/modeling/__tests__/CreateZeebeCallActivityBehaviorSpec.js
> +      it('should not duplicate extensionElements', inject(function(canvas,
Well in this case the copied callActivity already has a `calledElement`. The test case aims at testing that this existing element is not duplicated. 

I rephrased to `should re-use existing extensionElements`

2020-11-13 14:43 UTC, MaxTru commented on client/src/app/tabs/bpmn/custom/modeling/__tests__/UpdatePropagateAllChildVariablesBehaviorSpec.js
> +      describe('parameter not explicitly set (legacy callActivity)', function() {
:+1: Done

2020-11-13 15:10 UTC, MaxTru commented on client/src/app/tabs/bpmn/custom/modeling/__tests__/UpdatePropagateAllChildVariablesBehaviorSpec.js
> +  describe('set propagateAllChildVariables to false', function() {
True - done (by the way: this shall only be tested for non-legacy call activities. Legacy callActivities will be displayed correctly in the PropertiesPanel, but not auto-migrated [the user may click on the toggle if he/she wants that])

2020-11-13 15:28 UTC, MaxTru commented on client/src/app/tabs/bpmn/custom/modeling/behavior/CreateZeebeCallActivityBehavior.js
> +    if (!calledElement) {
Done

2020-11-13 15:35 UTC, MaxTru commented on client/src/app/tabs/bpmn/custom/modeling/behavior/UpdatePropagateAllChildVariablesBehavior.js
> +        !!properties.propagateAllChildVariables === false) {
I want to make sure that we also not execute this behavior in case that propagateAllChildVariables is undefined. So `!!undefined` will be `false`.

I don't see a need to change this? or maybe I dont udnerstand the comment.

2020-11-13 15:37 UTC, MaxTru commented on client/src/app/tabs/bpmn/custom/modeling/behavior/UpdatePropagateAllChildVariablesBehavior.js
> +  // Behavior when adding outputParmaeters ////////////////////////////////////
Thx, done

2020-11-13 15:38 UTC, MaxTru commented on client/src/app/tabs/bpmn/custom/modeling/behavior/UpdatePropagateAllChildVariablesBehavior.js
> +    // (1) Check whether we are in a CallActivity and un-toggling propAllChildVariables
Thanks. I clarified it.

2020-11-13 15:50 UTC, MaxTru commented on client/src/app/tabs/bpmn/custom/modeling/behavior/UpdatePropagateAllChildVariablesBehavior.js
> +     (objectsToAdd && objectsToAdd.length > 0 && !is(objectsToAdd[0], 'zeebe:Output')) ||
Good point! I updated that. (But I also don't know => I think it is not possible in the current option in the propertiesPanel to perform such an operation. So this is just a code change for robustness then - still valid)

2020-11-13 15:50 UTC, MaxTru commented on client/src/app/tabs/bpmn/custom/modeling/behavior/UpdatePropagateAllChildVariablesBehavior.js
> +  // Revert behavior when adding outputParmaeters ////////////////////////////////////
Done thanks

2020-11-13 15:57 UTC, MaxTru commented on client/src/app/tabs/bpmn/custom/properties-provider/__tests__/InputOutputSpec.js
> +import contextPadModule from 'bpmn-js/lib/features/context-pad';
Unfortunetly there is a dependency when using the custom Modules

2020-11-13 15:59 UTC, MaxTru commented on client/src/app/tabs/bpmn/custom/properties-provider/__tests__/OutputParameterToggleSpec.js
> +
I don't think so? There is not `it(...)` before right?

2020-11-16 10:11 UTC, pinussilvestrus commented on client/src/app/tabs/bpmn/custom/modeling/behavior/UpdatePropagateAllChildVariablesBehavior.js
> +        !!properties.propagateAllChildVariables === false) {
got it

2020-11-16 10:13 UTC, pinussilvestrus commented on client/src/app/tabs/bpmn/custom/modeling/behavior/UpdatePropagateAllChildVariablesBehavior.js
> +        !!properties.propagateAllChildVariables === false) {
So why then not simply checking for `!properties.propagateAllChildVariables`?

2020-11-16 10:47 UTC, pinussilvestrus commented on client/src/app/tabs/bpmn/custom/properties-provider/__tests__/OutputParameterToggleSpec.js
> +
Don't we follow this pattern?

```js
beforeEach();


describe() {
  
  it();


  it();

}


describe() {

  it();


  it();

}
```

So also new lines between each describe?

2020-11-16 10:48 UTC, pinussilvestrus commented on client/src/app/tabs/bpmn/custom/modeling/__tests__/CreateZeebeCallActivityBehaviorSpec.js
> +import customModules from '../../';
We should check what modules we really use. I can think that we only need 

* modelingModule
* copyPasteModule
* coreModule
* zeebeModdleExtensions
* customModelingModule

So not even the customModules, because we are only relying on the custom behaviors. I tried it out locally and the tests still runs as expected.

2020-11-16 10:51 UTC, pinussilvestrus commented on client/src/app/tabs/bpmn/custom/modeling/__tests__/UpdatePropagateAllChildVariablesBehaviorSpec.js
> +          clickPropagateAllChildVariablesToggle(container);
I thought a bit about this thingy. 

I think we should test this whole behavior without the need for the properties panel as well. The behavior is handling it generally after firing the `command` therefore it should be possible to test it by just executing the command via `commandStack`. What do you think?

2020-11-16 10:53 UTC, pinussilvestrus commented on client/src/app/tabs/bpmn/custom/modeling/__tests__/UpdatePropagateAllChildVariablesBehaviorSpec.js
> +import customModules from '../../';
Cf. comment https://github.com/zeebe-io/zeebe-modeler/pull/271/files#r524110970

2020-11-16 10:54 UTC, pinussilvestrus commented on client/src/app/tabs/bpmn/custom/properties-provider/__tests__/InputOutputSpec.js
> +import contextPadModule from 'bpmn-js/lib/features/context-pad';
Cf. comment https://github.com/zeebe-io/zeebe-modeler/pull/271/files#r524110970

2020-11-17 12:25 UTC, MaxTru commented on client/src/app/tabs/bpmn/custom/modeling/behavior/UpdatePropagateAllChildVariablesBehavior.js
> +        !!properties.propagateAllChildVariables === false) {
True. Still the current way makes it explicit. I don't mind too much but don't feel this would benefit from the change. Let me know if you think about it differently.

2020-11-17 12:56 UTC, MaxTru commented on client/src/app/tabs/bpmn/custom/properties-provider/__tests__/OutputParameterToggleSpec.js
> +
:+1: 
Done

2020-11-17 13:10 UTC, MaxTru commented on client/src/app/tabs/bpmn/custom/modeling/__tests__/UpdatePropagateAllChildVariablesBehaviorSpec.js
> +          clickPropagateAllChildVariablesToggle(container);
In general I agree. But when looking at it I figured that we currently don't test in `bpmn-js-properties-panel` that for example `properties-panel.update-businessobject` is fired once the toggle is clicked. That is why I decided to go use "integration test" approach. 

I think we could:
A) leave as is
B) Test via commandStack and add test that `properties-panel.update-businessobject` is fired when clicking on toggle
C) Leave as is + additionally add the test via `commandStack.execute(...)` 

Personally I don't think the dependencies here are a big issue, but we gain a more complete test coverage. I would therefore propose to leave it. But I am open for discussion. WDYT?

2020-11-17 13:18 UTC, MaxTru commented on client/src/app/tabs/bpmn/custom/modeling/__tests__/CreateZeebeCallActivityBehaviorSpec.js
> +import customModules from '../../';
Very true, thanks

2020-11-17 13:32 UTC, MaxTru commented on client/src/app/tabs/bpmn/custom/properties-provider/__tests__/InputOutputSpec.js
> +import contextPadModule from 'bpmn-js/lib/features/context-pad';
Thanks. 

I cleaned it up.

2020-11-17 13:35 UTC, MaxTru commented on client/src/app/tabs/bpmn/custom/modeling/__tests__/UpdatePropagateAllChildVariablesBehaviorSpec.js
> +import customModules from '../../';
Done. Thx

2020-11-19 08:17 UTC, MaxTru commented on client/src/app/tabs/bpmn/custom/modeling/__tests__/UpdatePropagateAllChildVariablesBehaviorSpec.js
> +          clickPropagateAllChildVariablesToggle(container);
Makes sense. 

But doing this, I will also test that the "Add output parameter Button" and the "Propagate All Child Variables Toggle" execute the respective commands + emit the expected payload. Otherwise that would be a blind spot of the testing approach.

2020-11-19 11:04 UTC, MaxTru commented on client/src/app/tabs/bpmn/custom/modeling/__tests__/UpdatePropagateAllChildVariablesBehaviorSpec.js
> +          clickPropagateAllChildVariablesToggle(container);
Thought about this again and also asked the team.

I will keep the current implementation as integration test. Will add another test as encapsulated test of the behavior only (mocking the eventBus)

2020-11-19 13:22 UTC, MaxTru commented on client/src/app/tabs/bpmn/custom/modeling/__tests__/UpdatePropagateAllChildVariablesBehaviorSpec.js
> +          clickPropagateAllChildVariablesToggle(container);
Done :+1:

2020-11-24 12:59 UTC, pinussilvestrus approved these changes
👏  I especially like the amount and quality of the tests now 👍

2020-11-24 12:59 UTC, merged