feat(deployment): use last endpoint deployed for all files
zeebe-io/zeebe-modeler pull request #285
Opened 2021-01-07 14:06 UTC by azeghers

In accordance with https://github.com/bpmn-io/internal-docs/issues/224, this PR aligns the Zeebe Modeler deployment plugin with the Camunda Modeler one.

__Which issue does this PR address?__

Closes #227 

__Acceptance Criteria__

* [ ] Corresponds to the concept 
* [ ] Corresponds to the design 

__Definition of Done__

* [ ] corresponds to [the design principles](https://github.com/bpmn-io/design-principles)
* [ ] corresponds to [the code standards](https://github.com/bpmn-io/bpmn-js/blob/master/.github/CONTRIBUTING.md#creating-a-pull-request)
* [ ] passes Continuous Integration checks
* [ ] available as feature branch on GitHub
  * [ ] contains the cleaned up commit history
  * [ ] commit messages satisfy our [commit message guidelines](https://www.conventionalcommits.org/)
  * [ ] a single commit closes the issue via Closes #issuenr

2021-01-07 16:12 UTC, azeghers commented
Not yet ready for review

2021-01-13 14:01 UTC, azeghers commented
Small finding, the [test covering this section](https://github.com/zeebe-io/zeebe-modeler/blob/develop/client/src/plugins/zeebe-plugin/deployment-plugin/__tests__/DeploymentPluginSpec.js#L84-L112) used to only test a single saved endpoint, which wasn't very useful back when the deployment tool could handle multiple endpoints.
The test is now appropriate without modification.

2021-01-15 09:05 UTC, pinussilvestrus commented
Just to understand it correctly: We ignore the multi-endpoint concept for now and use the same endpoint globally for every file, right? Because this is what I experienced

* Create a deployment for diagram1.bpmn --> _endpointA_ is saved
* Open deployment modal for diagram2.bpmn --> already existing _endpointA_ is used as default
* Modifiy the endpoint configuration for diagram2.bpmn --> _endpointA_ is updated
* Open deployment modal diagram1.bpmn --> modified _endpointA_ is used

And so on. So basically there is currently only one global endpoint being used for all diagrams. Is this the intended behavior?

2021-01-15 13:54 UTC, azeghers commented
@pinussilvestrus That's correct.

2021-01-20 10:47 UTC, pinussilvestrus commented on client/src/plugins/zeebe-plugin/deployment-plugin/DeploymentPlugin.js
> +      config: await this.getDefaultConfig(savedConfig, tab),
I'm not 100% sure whether this will cause any trouble in the future (async object property assignment).

I'd make it explicit

```js
const defaultConfiguration = await this.getDefaultConfig(savedConfig, tab);

const modalState = {
  config: defaultConfiguration
  // ...
}
```

2021-01-20 10:47 UTC, pinussilvestrus commented on client/src/plugins/zeebe-plugin/deployment-plugin/DeploymentPlugin.js
> +      endpoint = previousEndpoints[0];
I think we never know for sure that _every_ property is set in the last used endpoint. Therefore I would make it safe to keep missing default values from above.

```js
endpoint = {
  ...endpoint,
  previousEndpoints[0]
}
```

2021-01-20 10:47 UTC, pinussilvestrus commented
Works well for me 👍  Just some thoughts for possible code changes.

2021-01-21 07:54 UTC, pinussilvestrus commented on client/src/plugins/zeebe-plugin/deployment-plugin/DeploymentPlugin.js
> +      endpoint = previousEndpoints[0];
Sorry, it has to be

```js
endpoint = {
  ...endpoint,
  ...previousEndpoints[0]
}
```

2021-01-21 08:16 UTC, nikku commented on client/src/plugins/zeebe-plugin/deployment-plugin/DeploymentPlugin.js
> +      endpoint = previousEndpoints[0];
Not sure if this works as expected, as different properties may be required per endpoint type (i.e. authentication). Please double-check that before accepting this suggestion.

2021-01-21 16:26 UTC, azeghers commented on client/src/plugins/zeebe-plugin/deployment-plugin/DeploymentPlugin.js
> +      endpoint = previousEndpoints[0];
I tested both and don't see the difference, with or without credential save.
Let me know what I should try out specifically, or if the current version is acceptable.

2021-01-25 12:27 UTC, nikku requested changes

2021-01-25 12:27 UTC, nikku commented on client/src/plugins/zeebe-plugin/deployment-plugin/DeploymentPlugin.js
> +    const defaultConfiguration = await this.getDefaultConfig(savedConfig, tab);
We should have test coverage for this behavior, right?

2021-01-25 12:28 UTC, nikku commented on client/src/plugins/zeebe-plugin/deployment-plugin/DeploymentPlugin.js
> +      endpoint = previousEndpoints[0];
For the moment, let's accept the current version.

2021-01-25 12:49 UTC, nikku commented on client/src/plugins/zeebe-plugin/deployment-plugin/DeploymentPlugin.js
> +    const defaultConfiguration = await this.getDefaultConfig(savedConfig, tab);
Should be covered by existing tests as @azeghers mentioned.

2021-01-25 12:50 UTC, nikku approved these changes
Looks good.

2021-01-25 12:50 UTC, merged